---
# tasks file for k8s_master
- package:
     name: "docker"
     state: present
- service: 
     name: "docker"
     state: started
     enabled: yes
- name: configuring repo for k8s
  yum_repository:
    name: Kubernetes
    description: K8s repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg


- command: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

- service:
     name: "kubelet"
     state: started
     enabled: yes
- command: kubeadm config images pull
- copy:
     dest: "/etc/docker/daemon.json"
     content: |
      {
              "exec-opts": ["native.cgroupdriver=systemd"]
      }
- service:
     name: "docker"
     state: restarted
- package:
     name: "iproute-tc"
     state: present
- copy: 
     dest: "/etc/sysctl.d/k8s.conf"
     content: |
             net.bridge.bridge-nf-call-ip6tables = 1
             net.bridge.bridge-nf-call-iptables = 1

- command: sysctl --system
- command: kubeadm init --pod-network-cidr=10.240.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem
  register: x
    #  - debug:
    #     var: x
- command: mkdir -p $HOME/.kube
- command: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
- shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config
- command: kubectl apply  -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
- name: Generating token for k8s
  shell: kubeadm token create --print-join-command
  register: token_k8s_master

- name: Token
  debug:
      msg: "{{ token_k8s_master.stdout }}"

- name: adding host for token in
  add_host:
      name: "token"
      token_k8s: "{{ token_k8s_master.stdout }}"
