---
# tasks file for k8s_slave
- package:
     name: "docker"
     state: present
- service: 
     name: "docker"
     state: started
     enabled: yes
- name: configuring repo for k8s
  yum_repository:
    name: Kubernetes
    description: K8s repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- command: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

- service:
     name: "kubelet"
     state: started
     enabled: yes
- command: kubeadm config images pull
- copy:
     dest: "/etc/docker/daemon.json"
     content: |
      {
              "exec-opts": ["native.cgroupdriver=systemd"]
      }

- service:
     name: "docker"
     state: restarted
- package:
     name: "iproute-tc"
     state: present
- copy: 
     dest: "/etc/sysctl.d/k8s.conf"
     content: |
             net.bridge.bridge-nf-call-ip6tables = 1
             net.bridge.bridge-nf-call-iptables = 1

- command: sysctl --system
- name: Getting token
  debug:
      msg: "{{ hostvars['token']['token_k8s'] }}"
  register: token_final
- name: Starting kubeadm join with token
  command: "{{ token_final.msg }}"
